name: Build and Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install deps
      working-directory: ./frontend
      run: npm ci
    - name: Build
      working-directory: ./frontend
      run: npm run build
    # Add Azure Static Web Apps deploy action separately in Azure portal binding
